### PR TITLE
Enable Foreman debug logging during installation

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ekohl** [comment]
Does this work with all supported versions?

**Comment by domcleal** [comment]
No, but it's only enabled with a recent FOREMAN_VERSION.

**Comment by ekohl** [comment]
Don't we get less logging now and should we keep the ugly hack in behind a version check?

**Comment by domcleal** [comment]
Ah, you mean in the hammer tests file?  We'd get less logging on old versions if we ran the Hammer tests there, but we only run them against nightlies today - only the fb-install-foreman file's run for old releases.

**Comment by ekohl** [comment]
Fair enough. :+1:

**Comment by mmoll** [comment]
merged as 3427492, thanks @domcleal!

**Pull request closed without merging**
