### PR TITLE
Install openjdk-8-jre-headless from jessie-backports with Puppet nightly

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by mmoll** [comment]
If Java 8 is required, shouldn't the dependencies of the puppetserver packages get adjusted? IIRC it depends on some openj* instead of a generic Java package anyway (thus preventing the usage of an Oracle JRE package).

**Comment by domcleal** [comment]
It does depend on openjdk-8-jre-headless specifically, but by default apt-get won't resolve dependencies out of jessie-backports without the `-t` option or (probably) changing the source policy.

I don't think it's a good process to install the puppetserver package, but for now I'm just mirroring the steps in Puppet's patch. It may change again or need changing closer to release to match their install docs.

**Comment by mmoll** [comment]
I see... So my habit always using "-t jessie-backports" when doing updates kept that problem away from me ;)

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
