### PR TITLE
Added run-script bats test

### PR DESCRIPTION
**Pull request by lzap**
For some downstream testing, I need to run script downloaded from (safe)
internal http/https URLs. This test adds this ability, might be helpful for
others I think.

### CODE REVIEW

**Comment by lzap** [comment]
Damn does not work... I need to export variables.

**Comment by lzap** [comment]
Fixed now.

**Comment by ekohl** [comment]
The aim is to run bats for tests, but this appears to abuse it to do random other tasks. Especially running it in screen strikes me as odd. I don't mind additional scripts, but maybe we should group this in a contrib directory. @domcleal / @mmoll what do you think?

**Comment by mmoll** [comment]
this is like `curl | sh` :scream_cat: 
:-1:

**Comment by domcleal** [comment]
Yeah, I don't get what or how it tests anything.

**Pull request closed without merging**
